### ISSUE TITLE
Login with Keplr and blank page

### ISSUE THREAD

**Issue by CodeBanBan** [g-luca/go-find#10]
Login with keplr wallet on chrome and see blank page

**Comment by g-luca** [comment]
Hi, this might be probably a Keplr issue, first of all, you should verify that:
 - Keplr extension is updated to the latest version
 - Chrome is updated to the latest version
 
 If the problem persists, more information is needed:
 - Chrome version
 - Keplr version
 - OS (Windows/MacOs/Linux)
 - A screen of the error
