### ISSUE TITLE
unable login

### ISSUE THREAD

**Issue by WildHashGhost-Cica** [g-luca/go-find#11]
I tried to login, but I got error , I couldn't login with 24 phrase words too, I got, try again 2 times

**Comment by g-luca** [comment]
Can you please provide more info of what you have done?
- Did you register a go-find.me account or with Keplr?
- If you registered a go-find.me account, did you save the profile on chain (paying the transaction fees)?
- Did you register and log out without saving the profile on chain and tried to log back in? If so, please rember when signin in to use "Sign In with your address".

**Comment by WildHashGhost-Cica** [comment]
Yes, I registered I saved my profile and I had some DSM in my wallet, I couldn't use keplr for registration. I logged out, and when I want to login again, I got error my password or dtag isn't good, I wrote it done when I completed the registration, I can't login again

**Comment by WildHashGhost-Cica** [comment]
I saved my profile of course

**Comment by g-luca** [comment]
If you created a new Go-find.me account (generating a brand new seed) and you logged out without having saved the desmos profile on chain, you need to click "Sign In with your address".

If you don't remember you can:
1. Do again the signup process importing the previous seed
2. Import the previous seed into Keplr, and then sign in using Keplr
