### ISSUE TITLE
airdrop

### ISSUE THREAD

**Issue by msdegtyarev** [g-luca/go-find#12]
accidentally removed the desmos network from KEPLR after receiving the airdrop.
now I can not restore the network wallet address to which it was credited.
huge request for help.
Wallet address where the airdrop is credited desmos13luexrkj7zr7cdmg9kw70gslkljn9sdl6tm3dn

an address that is constantly being restored to Kepler
desmos1s867hv4pwhepalyng08zex7a75cg65d5z4rl7l

the address for which the airdrop was charged:
osmo1t85ktfswk2def6z2685xgy9npau84zna5ewukn

**Comment by g-luca** [comment]
You can restore the Desmos Network profile at any time by refreshing the page.
But it looks like you have changed Keplr account, if you have multiple Keplr accounts try :
 - logout from go-find.me
 - switch Keplr account
 - log in again

This is for all your accounts, if this doesn't work either, are you sure you didn't delete the Keplr account you used to access go-find.me the first time and that you used to claim the airdrop?
If so, and you haven't the mnemonic of that account, there's nothing you can do, unfortunately.

**Comment by msdegtyarev** [comment]
I did not delete the account, but after receiving the airdrop, I deleted the desmos network from the account in Kepler
Wallet address where the airdrop is credited desmos13luexrkj7zr7cdmg9kw70gslkljn9sdl6tm3dn

an address that is constantly being restored to Kepler
desmos1s867hv4pwhepalyng08zex7a75cg65d5z4rl7l

the address for which the airdrop was charged:
osmo1t85ktfswk2def6z2685xgy9npau84zna5ewukn

**Comment by msdegtyarev** [comment]
and when trying to restore the desmos network to Kepler, it restores another account

**Comment by msdegtyarev** [comment]
![image](https://user-images.githubusercontent.com/95098028/143678526-0288f43f-0bdd-4751-9af6-6fc8f7a929d8.png)

**Comment by msdegtyarev** [comment]
![image](https://user-images.githubusercontent.com/95098028/143678531-f2c9f96c-7d98-4bf8-89d2-a66502ca5f30.png)

**Comment by msdegtyarev** [comment]
![image](https://user-images.githubusercontent.com/95098028/143678575-1f287932-6196-4e0f-bc89-7194f0a4d1e8.png)
