### ISSUE TITLE
airdrop

### ISSUE THREAD

**Issue by msdegtyarev** [g-luca/go-find#14]
accidentally removed the desmos network from KEPLR after receiving an airdrop.
now I cannot recover the network wallet address to which it was credited. When trying to connect Kepler on go-find, it connects a new desmos blockchain, which does not have an airdrop.
And when I go to search through the password, I see my airdrop, but when I try to connect the desmos blockchain, I get an error - "Keplr permission denied"
I have one Kepler account.
I tried to remove desmos from Kepler, exit it, and connect again, but it is impossible to restore it constantly connects desmos to the wrong address.
huge request for help.
The address of the wallet to which the distribution is credited desmos13luexrkj7zr7cdmg9kw70gslkljn9sdl6tm3dn

an address that Kepler constantly recovers
desmos1s867hv4pwhepalyng08zex7a75cg65d5z4rl7l

the address to which the distribution was credited:
osmo1t85ktfswk2def6z2685xgy9npau84zna5ewukn

**Comment by msdegtyarev** [comment]
![image](https://user-images.githubusercontent.com/95098028/143763629-0bb53314-b983-4908-9545-0dc128e67e99.png)
pulls up this account

**Comment by msdegtyarev** [comment]
![image](https://user-images.githubusercontent.com/95098028/143763661-044eff2b-4995-4937-8a56-866c22a1a92e.png)
the airdrop is on this

**Comment by msdegtyarev** [comment]
How can you transfer the distribution from desmos13luexrkj7zr7cdmg9kw70gslkljn9sdl6tm3dn to desmos1s867hv4pwhepalyng08zex7a75cg65d5z4rl7l? This would fix the problem.

**Comment by g-luca** [comment]
You can't transfer distribution without having access to the wallet. 
Also removing the network doesn't actually change the desmos address, it's generated only by the seed.
You can try to:
1. logout from go-find.me
2. create a new Keplr account with the seed of the right account
3. **select** that Keplr account
4. login again

If with this process you don't have the right desmos address, you may actually generated that account with a different seed.
