### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by greg16100** [g-luca/go-find#19]
I lost my password but I have got my seed . What to do to recover or reset the password ?

**Comment by g-luca** [comment]
Hi, you can easily recover your password here: http://go-find.me/register , you just have to signup again
Pay attention to:
1. If you saved the profile on chain, you have to click "Already have a Desmos Profile". (verify if you saved on chain here: https://explorer.desmos.network/accounts/{desmosaddress} )
2. Import your seed, you can't use another one
