### ISSUE TITLE
AIRDROP

### ISSUE THREAD

**Issue by RHoldboy** [g-luca/go-find#26]
Having great trouble claiming the airdrop.
Trying to use the Keplr wallet method. I have used a valid address to get a grant but when I connect chains it is linked to the wrong Keplr wallet. Thus I get message saying no valid claim because it is looking at the wrong wallet. If I try to start again it says a grant has already been issued to the other Desmos address. HELP!!

**Comment by ericm301** [comment]
I have the same problem:
- I created one Desmos wallet on the app, but it won't connect to Keplr.
- I created another using go-find.me, and I can see it is Keplr, but go-find.me says there's a pending claim on the other wallet!

**Comment by RHoldboy** [comment]
Lets hope someone helps us.

**Comment by ericm301** [comment]
I just managed to claim mine!
Here's what worked for me:
- I have Keplr extension installed on Google Chrome.
- I selected my eligible wallet in Keplr, with the Desmos id also selected
- I went to https://go-find.me and chose Keplr to login, and entered my password in Keplr
- The webpage asked for my DTag and password (Desmos) and I was able to login.
- Then it told me I had to update my profile, but I needed DSM to do that.
- I had some in my other wallet and used Keplr to move it, and updated my profile (I just added s'ting stupid to the bio).
- Then I was able to add my eligible chain (Osmosis address) and claim the drop!

Hope this helps!

**Comment by RHoldboy** [comment]
I am still battling with it. Thanks for your help.

**Comment by g-luca** [comment]
> I just managed to claim mine! Here's what worked for me:
> 
> * I have Keplr extension installed on Google Chrome.
> * I selected my eligible wallet in Keplr, with the Desmos id also selected
> * I went to https://go-find.me and chose Keplr to login, and entered my password in Keplr
> * The webpage asked for my DTag and password (Desmos) and I was able to login.
> * Then it told me I had to update my profile, but I needed DSM to do that.
> * I had some in my other wallet and used Keplr to move it, and updated my profile (I just added s'ting stupid to the bio).
> * Then I was able to add my eligible chain (Osmosis address) and claim the drop!
> 
> Hope this helps!

That's actually the correct path if you requested the grant to the wrong address, send your grant balance to your Desmos Keplr address with the same seed of your eligible address.
Once done, you just need to save the new profile, connect the eligible address, and claim!

If you need further help, please use [Discord](https://discord.com/channels/653856306553159696/831767640288395314/831768121358417990), we can provide faster support for airdrop
