### ISSUE TITLE
 Your actual balance cannot cover transaction fees.

### ISSUE THREAD

**Issue by okshock** [g-luca/go-find#28]
Your actual balance cannot cover transaction fees.  That's what it says when I try to create a profile

**Comment by g-luca** [comment]
You actually need DSM to pay transaction fees, and this applies to all the go-find feature (profile save, chain link, etc...).
If you are eligible for the airdrop however, you can click the airdrop button and request a grant to pay the initial profile setup fees.
If you are not eligible for the airdrop, you'll have to wait until early 2022 to buy DSM on Osmosis.

**Comment by okshock** [comment]
Thanks Luca!
