### ISSUE TITLE
How To Get DSM tokens 

### ISSUE THREAD

**Issue by TiffanyDreams1** [g-luca/go-find#3]
Where do I get Desmos (DSM) tokens.

Thank you. 
Olga.

**Comment by g-luca** [comment]
Hi Olga,
right now the only way to buy DSM is with the [Desmos Airdrop](https://medium.com/desmosnetwork/announcing-dsm-airdrop-to-the-interchain-community-39d9837dcc5c) or with the future listing on Osmosis by the end of the year/early 2022.
If you want to stay updated, there's the official [Desmos Discord channel](https://t.me/DesmosITA/4772)
Also some validators on Discord are sending tokens to users that just wanna create a Desmos profile, try asking there!

**Comment by TiffanyDreams1** [comment]
Hi

Thanks for getting back.  I joined Desmos's discord and was sent some from there to create my profile.  

Many thanks for your help.  

Olga Graham 

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
