### ISSUE TITLE
airdrop desmos

### ISSUE THREAD

**Issue by ufraaa** [g-luca/go-find#31]
Hello I have a problem I have done all the necessary procedure to claim the airdrop I changed the nick name I connected the cosmos blockchain I click on airdrop I enter my atom address and it tells me that I have 120 desmos to claim but when I click on claim it comes out: There are no claimable airdrops left to claim ...... and 'already many times that I try but nothing ...... why?

**Comment by g-luca** [comment]
You have to connect **all** the eligible address to claim **all** the airdrop ("Connect Blockchain"), once done you should be able to claim the airdrop without problems.
If still not works please check if your profile has been saved on chain correctly here: https://explorer.desmos.network/ and if not, just logout and sign in again

**Comment by ufraaa** [comment]
ciao scusami il ritardo.......... ti dico ho fatto tutte le procedure in modo corretto ho il portafoglio keplr con lo stesso seed......collego la blockchain mi dice che ho 120 dsm da rivendicare clicco su airdrop e mi dice che non ci sono piu dsm rimasti da rivendicare ma io non ne ho nessuno sul mio wallet .........sono ormai stanco di continuare a riprovare a fare le stesse cose credo che a sto punto chiudero' tutto.....grazie comunque per il tuo aiuto

**Comment by ufraaa** [comment]
ah scusa ho anche verificato su  https://explorer.desmos.network il mio profilo che è stato salvato in modo corretto e ho anche provato lo stesso a disconnettermi e accedere di nuovo. ciao grazie

**Comment by ufraaa** [comment]
ah scusa ho anche verificato su https://explorer.desmos.network il mio profilo che è stato salvato in modo corretto e ho anche provato lo stesso a disconnettermi e accedere di nuovo ma nulla vorrei solo aggiungere ,se puo' servire, dopo che mi esce la scritta: There are no claimable airdrops left to be claimed ,  la blockchain cosmos collegata si scollega da sola . ciao grazie

**Comment by g-luca** [comment]
Il problema allora è che non riesce a salvare il collegamento con Cosmos, che è essenziale per ricevere l'airdrop.
Le motivazioni principalmente possono essere 2:
1. Il profilo non è salvato, ma questo se hai controllato e ti risulta nell'explorer lo escluderei
2. La proof del chainlink non è valida, che potrebbe essere dovuta alla modifica di qualche parametro di Keplr (gas, fee, memo) durante la firma.

In ogni caso comunque vuol dire che sull'explorer dovresti vedere delle transazioni fallite sul tuo account, se riesci a girarmi i vari messaggi di errore sarebbe molto utile a capire il problema.
Altrimenti girami pure l'address o il dtag (qui o pure su [discord](https://discord.com/channels/653856306553159696/831767640288395314/831768121358417990) in dm Luca | GStake) che verifico io direttamente

**Comment by ufraaa** [comment]
buonasera, si esatto ci sono una serie di transazioni fallite ti giro l'adress cosi puoi dargli un occhio tu stesso , grazie
desmos19syng5dg88065vlsvnap22983trhsz59ty6syl     ufraaa e' il nick name

**Comment by g-luca** [comment]
Puoi riprovare a fare il chain link ora? ho fatto degli aggiornamenti.
Prima di provare però refresha un paio di volte la pagina così da assicurarti di avere la nuova versione.

Ricordati che è fondamentale che non modifichi **nessuno** di questi attributi (memo, gas, fees):
<img width="372" alt="Keplr screen" src="https://user-images.githubusercontent.com/19191465/146563431-fc886e76-26e7-4665-95ae-512f19a2fd7d.png">

**Comment by ufraaa** [comment]
mi spiace ho riprovato piu' volte ho refreshato la pagina ho fatto logout e sono rientrato e ti confermo anche di non avere mai modificato nessun parametro in keplr , ma nulla si comporta ancora come ti ho spiegato la volta scorsa

**Comment by ufraaa** [comment]
ok finalmente!!!!!! problema risolto grazie, ho creato un account su forbole x e sono riuscito a fare il claim.
