### ISSUE TITLE
Need to disconnect the airdrop address from my Go-find DSM address

### ISSUE THREAD

**Issue by NeetApe888** [g-luca/go-find#37]
Hi all, 

I mistakenly put my airdrop claim address in go-find me profile, thought it was just for check eligibilty.

How can i disconnect it? I have to claim through Forble, since the eligible address in that wallet.

**Comment by g-luca** [comment]
Hi, if you requested a grant for the wrong address you can just send the received DSM to the Forbole wallet.
Once sent, you will have the necessary DSM to pay the transaction fees to setup the profile, connect the eligible chains and get the airdrop. 

If you already connected the eligible chains to the wrong profile, make sure to delete them before proceed. 
Also if you spent your grant doing wrong transactions, please post your address here or dm me on Discord (Luca | GStake) and i'll send you some more DSM to pay the fees.
