### ISSUE TITLE
Problem with DSM Airdrop with Go-find.me

### ISSUE THREAD

**Issue by NeedYaFeed** [g-luca/go-find#39]
Whenever I refresh the page so that the page recognizes my DSM, from which I can create a profile, my DSM account balance is not displayed.
The site does not recognize my DSM even though I have the required DSM on the wallet.
What can I do?
Can someone help me with this?

**Comment by g-luca** [comment]
Hi, did you request the airdrop grant?
Can you verify [here](https://explorer.desmos.network/) if your address is saved on chain and your balance is actually > 0 ?

**Comment by ciccio1200000** [comment]
my land address is eligible for desmos airdrop. through go find me and using keplr i created a desmos account and received desmos for transactions. through osmosis I created the earth address. but i can't connect my desmos address with the ground blockchain. can you help me to solve the problem? thank you

**Comment by g-luca** [comment]
@ciccio1200000 Can you provide more info about the error? The new address added to Keplr matches the eligible address? 
 What error do you see in the explorer? (https://explorer.desmos.network/).
