### ISSUE TITLE
AirDrop error

### ISSUE THREAD

**Issue by AlekseyLoktin** [g-luca/go-find#42]
Hi guys! 

Something I have errors and can not do anything ))))
Need your support! 

"I used Keplr Wallet to apply too, the instructions on Medium are a bit confusing, especially the telegram bot doesn't work anymore. 

Information for Keplr Wallet users:
https://www.youtube.com/watch?v=9CnoS0Evj4w
You can follow this video, except for the section about the telegram bot

Steps:
1) https://go-find.me/
2) Click "Use Keplr
3) Choose your dtag (6-30 characters)
4) Click "Airdrop" to get some gas to start
5) Set up your profile 
6) connect your blockchain (select osmosis + Keplr & juno + Keplr)
7) Click the "Airdrop" button again + your osmosis address
8) Done! Wait for the DSM to arrive in your account"

**Comment by AlekseyLoktin** [comment]
![image](https://user-images.githubusercontent.com/96685831/149201308-c878a598-9edf-4a91-aeed-13b8e4434ab3.png)

**Comment by g-luca** [comment]
Hi, i don't get what issue you you having, these steps are actually right:

1. Click "Airdrop" and input your eligible address to get some gas to start
2. Once requested you may need to wait 10/20s and eventually refresh. After that you'll receive around 0.06DSM
3. Save up your profile with nickname/bio/images (optionally)
4. Connect your eligible blockchain, "Connect a Blockchain" button
5. Once connected, click again the "Airdrop" button and claim
6. Done! Wait 10/20s to receive your airdrop
Note: you need to connect all your eligible addresses to receive all the airdrop

If you are having errors, please provide more details

**Comment by AlekseyLoktin** [comment]
I will send you in order the screenshots that I see myself...

![image](https://user-images.githubusercontent.com/96685831/149289428-4a869f68-2a9c-429a-825e-2cf6f5787df4.png)

When registering the service offered to register a purse, I did so
On the further steps gives out an error ...

Also, I had previously installed a purse Keplr, tried and his purse address to use and no success found 

![image](https://user-images.githubusercontent.com/96685831/149289792-c416687a-9b3c-47ea-9d4b-293ea424821f.png)

![image](https://user-images.githubusercontent.com/96685831/149290335-91fd199c-0f63-4749-8bdb-7bbfea0bd5a4.png)

The next step and further attempts and combinations did not lead to success.

Tried the same way to perform all the actions from my mom's account and all the same ...

![image](https://user-images.githubusercontent.com/96685831/149290940-77cb23e4-60a7-4d4b-b459-e4feb1057dee.png)

I tried to describe all the steps and demonstrate everything I see myself... 

Need help and support and a million tickets to the moon ))

![image](https://user-images.githubusercontent.com/96685831/149291482-34f62567-2dd2-49a6-b4a3-272d73cfc5e7.png)

When trying to specify an address from an existing wallet Keplr gives a white screen

**Comment by g-luca** [comment]
You have to input your cosmos/kava/cro/etc.. address, not desmos.
That's why you are getting "Address not eligible"

**Comment by AlekseyLoktin** [comment]
I wrote above that I tried it both ways and each time the same error ...

![image](https://user-images.githubusercontent.com/96685831/149299092-f839dc7e-2d5c-4b74-ac94-eb336fc5e0ad.png)

**Comment by g-luca** [comment]
That cosmos address as far i can see is not eligible since is new. You have to input the cosmos (or cro, luna, etc..) that meet this requirements: https://medium.com/desmosnetwork/announcing-dsm-airdrop-to-the-interchain-community-39d9837dcc5c

**Comment by AlekseyLoktin** [comment]
I read this article... 
It says that if the wallet is custom, there are no options, am I right to understand that this is a guide to action and there is no point in looking further for a solution?
It would be a waste of time, nothing more?

**Comment by g-luca** [comment]
If you have an eligible address, but a custom wallet you can import the seed on one of the supported wallets (Keplr, Forbole X, Cosmostation). Then you can claim with any of these

**Comment by AlekseyLoktin** [comment]
I just got the notification from you now.
I have the wallet I submitted to you earlier.
What do I need to do with it to make it work?

вс, 16 янв. 2022 г. в 17:37, Luca Graziotti ***@***.***>:
