### ISSUE TITLE
Balance not updated

### ISSUE THREAD

**Issue by Flydexo** [g-luca/go-find#44]
I connected my kepler wallet and my balance is 0 DSM but I have 16 DSM on my wallet you can check: desmos1dxxlkd4r7jcdjmn9n2ses6gy8yztsrfh9676n8

**Comment by g-luca** [comment]
Hi, now should work. The backend parser missed that block and didn't update your balance.
Now as you can see here is correct https://explorer.desmos.network/accounts/desmos1dxxlkd4r7jcdjmn9n2ses6gy8yztsrfh9676n8

**Comment by Flydexo** [comment]
Thanks
