### ISSUE TITLE
Can't do anything because this error pops up :

### ISSUE THREAD

**Issue by Sephix2005** [g-luca/go-find#45]
![image](https://user-images.githubusercontent.com/63220129/149656226-45e8cd43-df74-498d-8195-084bcba621cc.png)

What should i do ?
Can't get rewards, nor delegate or undelegate, even if i have 3 DSM available for fees

**Comment by g-luca** [comment]
I actually never seen this error, do you see these transactions on the explorer?
https://www.mintscan.io/desmos
