### ISSUE TITLE
DSM: Account balance not showing up on go-find.me

### ISSUE THREAD

**Issue by robespierreAlgo** [g-luca/go-find#46]
Dear Support, I am not able to save the account on the chain using go-finde.me to claim the airdrop.
I sent the request, which has been granted 2 days ago. 
After refresh and retrying again today I see no other option but to write you.

The related cosmos address is cosmos1h42awjtvmqt6e0fhqhevl0p9dpwxn9ux5hr872
Dsm: desmos1h42awjtvmqt6e0fhqhevl0p9dpwxn9uxq0whfj
dtag: robesp123

I have 0.06 DSM on Keplr which do not show up on go-find.me and if I try to save the account I get: 
"Your actual balance cannot cover transaction fees"

Thanks!

**Comment by g-luca** [comment]
Hi, your balance is >0 so should not have problem with fees, let's try with common solutions:

1. Logout from go-find.me
2. If you have more Keplr accounts, try to switch 1/2 times between them and then select again the right one
3. Login again with Keplr

If still not work and you also don't see your DSM on the Keplr extension, try also to:

1.  Logout from go-find.me
2. Remove the Desmos Network (you need to select another network to delete desmos)
3. Refresh the page and login again, it will prompt a fresh Desmos-Keplr configuration

**Comment by robespierreAlgo** [comment]
Thanks, it worked shortly after having written the issue, without needing to do anything ! 
Grazie tante Luca, che figata di progetto!! Per ora programmo algoritmi per l'università di Vienna, ma penso di smettere tra qualche mesetto per dedicarmi alle blockchain ... il razzo sta partendo <3
