### ISSUE TITLE
I get an error when I receive an airdrop

### ISSUE THREAD

**Issue by mizunko333** [g-luca/go-find#47]
Hello!
I have a question.

I connected the Cosmos and Osmo blockchains and clicked on AirDrop.

But I got the following error:
“You are not the original creator the link for address cosmos1uxs476ndlkyly8wwfmc78flp8fyuwcshgkwthc”

![image](https://user-images.githubusercontent.com/97837099/149662498-90632c0d-4803-4a6f-ab2a-771c31c707e8.png)

How can I receive Airdrop?

**Comment by g-luca** [comment]
Hi, this usually happens when the eligible address is already connected to another Desmos account.
If you already have connected that address to another Desmos account, remove it from the old account and try again, should work

**Comment by mizunko333** [comment]
Thank you,
If I forget my previously created Desmos account, is there a way to get it? Please let me know if there is a way to find out.

**Comment by mizunko333** [comment]
I can't remember my old account name. Is there a way to find out?
Sorry for your inconvenience while you are busy.

**Comment by g-luca** [comment]
Yeah sorry, do you still have the seed of the old account? If so, you can easily recover that account.
You just have to open the Keplr extension -> user icon -> add account -> input the old seed -> save -> reopen the extension and switch to that account.
Then you just have to open go-find.me -> logout (if needed) -> sign in with Keplr -> now you'll be logged with the old profile -> remove the chain link.
Once done, you can switch again to the new account, and claim successfully the airdrop!

If you don't remember just the dtag/address, but just the go-find password, i can do a research to retrieve it.

**Comment by mizunko333** [comment]
Does your "seed" mean a mnemonic seed? Seeds haven't changed before and now.
When I tried to log in with "Use Kepler", a screen for entering dtag appeared, so I created it.

I may have logged in with another dtag before, but I don't remember because my memory is ambiguous.
How should I do?

**Comment by g-luca** [comment]
That's strange, you can actually save only 1 profile for seed(mnemonic) (unless you change derivation path). 
Anyway, i found these profiles connected to that cosmos address:

- `tatsunko3` (desmos126wv6xcsd8ledv27nj9ht8pntvx5e0tvzew87u), the older one
- `tatsunko` (desmos1g77kmapntcjtmsq80gqjwl5prsu44d3atv3j6f), the new one

If you remember your passwords for `tatsunko3` you should be fine!

**Comment by mizunko333** [comment]
Thank you for teaching me.

If the tatsunko3 password is correct, can I proceed?
If I enter the wrong PW, will I be taken to the password change screen and the seeding screen?
The seed hasn't changed, so when I enter it, it becomes the address of "desmos1g77kmapntcjtmsq80gqjwl5prsu44d3atv3j6f" and I can't log in.

![image](https://user-images.githubusercontent.com/97837099/150045635-20cf2cb3-37ec-4cec-a419-720d1575fe2a.png)
![image](https://user-images.githubusercontent.com/97837099/150045678-57f0ef94-e54b-4ab6-8695-f352b8230374.png)


Looking at the description on the top page, I deleted Kepler's desmos network and added it again.
Will this work change my wallet address?

![image](https://user-images.githubusercontent.com/97837099/150045936-0c41a4db-6ab2-4631-8352-43e2806f6586.png)

**Comment by g-luca** [comment]
Yes i see that the address is registered, so if you remember the password you can proceed without problems.

Updating the network didn't affected the address so that's very strange, are you using Keplr + Ledger with the new account?

**Comment by mizunko333** [comment]
At the beginning, I connected Kepler and registered, so I don't remember setting password. 
I'm not using Ledger and I haven't renewed my account. This is very strange if network changes do not change the address.

I don't know the PW, and the previous seed (it hasn't changed) now, does that mean I can't receive this airdrop?

**Comment by g-luca** [comment]
You already claimed the airdrop as you can see here: https://explorer.desmos.network/accounts/desmos126wv6xcsd8ledv27nj9ht8pntvx5e0tvzew87u . 
So in no-way you can claim it again, your only way is to recover that account.

Do you remember if you added the Desmos Network to Keplr on go-find for the first time? or did you loaded another Desmos configuration from another website? 
Because at this point if you remember that you always logged with Keplr, never changed seed or keplr account, i actually have no idea.

In order to have a different address from the same mnemonic you need to change the [derivation path](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) and this never changed on go-find, even with the Keplr remove/add action, it was necessary only to add a flag to fix an URL so is totally unrelated.
