### ISSUE TITLE
I can't log in go-find.me

### ISSUE THREAD

**Issue by MrzxWang** [g-luca/go-find#50]
When I input wallet password, then click "continue", it not have any react.

**Comment by g-luca** [comment]
Which browser do you use? It's a probably a bug on the error message, should warn the wrong wallet password.
If you are at the "Wallet Password" stage it means that the first password is correct, so you have to unlock only the wallet and this operation is made offline, so if the password is right the unlock is instant.

Anyway if you don't  remember the wallet password, you can always do a password reset:
1. go to https://go-find.me/register
2. click "Already have a Desmos Profile", and input your dtag
3. then choose your new passwords, and input your seed

If you can give me some info on which browser you are using, i'll fix the message asap.

**Comment by 0xWildhare** [comment]
https://go-find.me/register just takes me back to https://go-find.me/me
?

**Comment by MrzxWang** [comment]
chrome browser.



---Original---
From: "Luca ***@***.***&gt;
Date: Fri, Jan 21, 2022 21:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [g-luca/go-find] I can't log in go-find.me (Issue #50)




 
Which browser do you use? It's a probably a bug on the error message, should warn the wrong wallet password.
 If you are at the "Wallet Password" stage it means that the first password is correct, so you have to unlock only the wallet and this operation is made offline, so if the password is right the unlock is instant.
 
Anyway if you don't  remember the wallet password, you can always do a password reset:
  
go to https://go-find.me/register 

click "Already have a Desmos Profile", and input your dtag 

then choose your new passwords, and input your seed 
 
If you can give me some info on which browser you are using, i'll fix the message asap.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by g-luca** [comment]
> https://go-find.me/register just takes me back to https://go-find.me/me ?
> 
> edit: i am trying to reset the pw bc i am getting "Transaction error or wrong password"

You need to logout first, go to  https://go-find.me/me, click your profile icon on the navigation bar, logout.
Then you'll be able to open https://go-find.me/register and reset the password as explained before

**Comment by g-luca** [comment]
Fix deployed (you may need to refresh the page), thanks for reporting @MrzxWang !
If you need further assistance feel free to ask

**Comment by MrzxWang** [comment]
Thanks, it works.



---Original---
From: "Luca ***@***.***&gt;
Date: Sat, Jan 22, 2022 00:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [g-luca/go-find] I can't log in go-find.me (Issue #50)




 
Fix deployed (you may need to refresh the page), thanks for reporting @MrzxWang !
 If you need further assistance feel free to ask
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
