### ISSUE TITLE
Add Desmos Keplr configuration

### ISSUE THREAD

**Issue by Kumarsunil67** [g-luca/go-find#54]
Help me 
How to add desmos chain in my kaplr extension

**Comment by g-luca** [comment]
Hi you can load the Desmos Keplr configuration in 2 ways:

1. Open go-find.me (if you are logged in, logout), click "Use Keplr". This will automatically prompt the Keplr request to add the Desmos configuration. If doesn't work, make sure that your Keplr extension is unlocked.

2. Open https://app.osmosis.zone/assets, connect you Keplr wallet, then at the Desmos row, click "Deposit". This will prompt the configuration. (You don't need to actually deposit any DSM)
