### ISSUE TITLE
Desmos Airdrop with Luna

### ISSUE THREAD

**Issue by 369firefish** [g-luca/go-find#55]
Hi

Just wondering if this has been fixed so that able to claim the airdrop as a result of having a few Luna tokens?

**Comment by g-luca** [comment]
Hi! Yes last week we released the Terra Station integration ( #51 ). 
You can now link your eligible luna address with the Terra Station extension (also Terra Station + Ledger) , and claim your airdrop!

We made the announcement on Twitter but actually not here, I apologize! 
If you need further help on the airdrop procedure, feel free to ask here
