### ISSUE TITLE
Cannot create Profile because DSM Balance not showing on website, but does show on Keplr

### ISSUE THREAD

**Issue by NicaNinja43** [g-luca/go-find#57]
On the Keplr Wallet, it shows my DSM balance, but on go-find.me/me it does not show balance so I cannot create a profile to be able to claim the AirDrop. I've logged out and back in several times. I have signed in with Keplr each time. Not sure what I need to do.

**Comment by g-luca** [comment]
Hi, it's pretty strange, can you check your balance on the explorer? https://explorer.desmos.network/
Go-find.me uses the same data source of the explorer, so if your balance is right on the explorer most probably is a bug with the browser or the extension.
Try to clean your browser cache and make sure your Keplr extension is updated, then logout and login again.

If the problem persist, can you provide more info about your browser?

- Name & version (ex. Chrome 98.0.1)
- Operating system (ex. Windows 11)

**Comment by NicaNinja43** [comment]
Balance on https://explorer.desmos.network/ shows 0, but under transactions it does show that I received the airdrop. 
<img width="333" alt="Screen Shot 2022-02-14 at 6 46 49 AM" src="https://user-images.githubusercontent.com/99520800/153867006-453a8abc-3224-46d0-af5e-f65bb88d9fc1.png">
<img width="486" alt="Screen Shot 2022-02-14 at 6 47 19 AM" src="https://user-images.githubusercontent.com/99520800/153867013-a7b086d1-e28f-4ae1-8f97-b2fb2d1e2409.png">
<img width="455" alt="Screen Shot 2022-02-14 at 6 48 54 AM" src="https://user-images.githubusercontent.com/99520800/153867187-a86ae461-0a6f-411b-912b-8fe211632d68.png">

**Comment by g-luca** [comment]
Thanks, now should be fixed, let me know
