### ISSUE TITLE
go-find.me

### ISSUE THREAD

**Issue by LeoBoi222** [g-luca/go-find#63]
I have forgotten my password but have the recovery phrase.  Is there any way to reset the password or restore the wallet with a recovery phrase?

**Comment by g-luca** [comment]
Sure, if you have your recovery phrase you can recover easily the account in 2 ways:

### Standard Signup
1. Open https://go-find.me/register
2. Click "Already have a Desmos Profile", and input your old username
3. Input your new password and then your recovery phrase (check if displays the right address, don't leave blank spaces at the end of the phrase)

Done, you have recovered your profile



### Keplr
1. Download Keplr ( https://www.keplr.app/download )
2. Create a keplr account with your recovery phrase
3. Login to go-find with Keplr

Done, you have recovered the same account


If you need further support, feel free to ask!
