### ISSUE TITLE
Image Upload Failed

### ISSUE THREAD

**Issue by lorenzomenegon** [g-luca/go-find#65]
![Screenshot 2023-04-21 alle 12 17 08](https://user-images.githubusercontent.com/106406454/233611760-daacdf6f-c278-4233-a624-99fd4ec2f97f.png)

I report that there is a 401 error when trying to make the image upload request to update the profile. 
I guess this problem is related to authentication with IPFS. is it possible to do a check?

**Comment by g-luca** [comment]
Thanks for the report! Fixed with [7c5c86b](https://github.com/g-luca/go-find/commit/7c5c86bf04d9c15a9b8d008f5ce10c0acdb62c9d)
